import Link from 'next/link';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarNav from './SidebarNav';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  {
    href: '/',
    label: 'Home',
    icon: (
      <svg width="28" height="28" fill="none" viewBox="0 0 24 24" stroke="#22372e" strokeWidth="2"><path d="M3 12L12 5l9 7"/><path d="M5 10v10a1 1 0 001 1h3m8-11v10a1 1 0 01-1 1h-3m-4 0h4"/></svg>
    ),
  },
  {
    href: '/agents-info',
    label: 'Chapters',
    icon: (
      <svg width="28" height="28" fill="none" viewBox="0 0 24 24" stroke="#22372e" strokeWidth="2"><path d="M6 4h12v16H6z"/><path d="M6 8h12"/></svg>
    ),
  },
  {
    href: '/prioritization-framework',
    label: 'Prioritization Framework',
    icon: (
      <svg width="28" height="28" fill="none" viewBox="0 0 24 24" stroke="#22372e" strokeWidth="2"><rect x="4" y="4" width="16" height="16" rx="4"/><path d="M8 8h8v8H8z" fill="#22372e"/></svg>
    ),
  },
  {
    href: '/use-cases',
    label: 'Use Cases',
    icon: (
      <svg width="28" height="28" fill="none" viewBox="0 0 24 24" stroke="#22372e" strokeWidth="2"><path d="M5 13l4 4L19 7" strokeLinecap="round" strokeLinejoin="round"/></svg>
    ),
  },
  {
    href: '/ai-success-blueprint',
    label: 'AI Success Blueprint',
    icon: (
      <svg width="28" height="28" fill="none" viewBox="0 0 24 24" stroke="#22372e" strokeWidth="2"><path d="M12 6v6l4 2" strokeLinecap="round" strokeLinejoin="round"/></svg>
    ),
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex bg-[#22372e]`}
      >
        {/* Sidebar Navigation */}
        <SidebarNav />
        {/* Main Content (with sidebar space) */}
        <div className="flex-1 md:ml-56">
          {children}
        </div>
      </body>
    </html>
  );
}
